name: Ruff
on: 
  pull_request:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
  mypy:
    needs: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: pip install mypy
      - run: mypy --install-types --non-interactive --explicit-package-bases --disable-error-code import-untyped .
