name: PR checks
on: 
  pull_request:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
  mypy:
    needs: ruff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - run: sudo apt install libsystemd-dev
      - run: pip install -r requirements.txt
      - run: pip install mypy==1.4.1  # 1.4.1 is the last version to support Python 3.7, which we run on AmpliPi
      - run: mypy --install-types --non-interactive --explicit-package-bases --ignore-missing-imports .
